app:
  name: short-app
  components: frontend
  replicas: 1
  port: 80
  limits:
    memory: "128Mi"
    cpu: "100m"

env: test
value:
  requirements:
    limits:
      memory: "128Mi"
      cpu: "100m"
users:
  - name: koT9
    role: admin
  - name: moT9
    role: manager
  
api:
  name: short-api
  image: antonlarichev/short-api
  version: latest
  components: backend
  replicas: 1
  port: 3000
  limits:
    memory: "500Mi"
    cpu: "200m"
  envs: 
    - DATABASE_URL

postgres:
  name: postgres
  image: posgres
  replicas: 1
  version: 16.0
  components: postgres
  port: 5432
  limits:
    memory: "500Mi"
    cpu: "300m"
  envs:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD

database:
  user: demo
  password: demo
  db: demo
  host: postgress-clusterip
  