
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels: 
    {{- include "chart.labels" . | indent 4  }}
data:
  name: {{  .Values.name |  upper | quote }}
  {{- if eq .Values.env "production"}}
  paymentTocken: "1234"
  {{- else }}
  paymentTocken: false 
  {{- end  }}
  {{-  with .Values.value.requirements.limits}}
  memory: {{.memory}}
  cpu: {{.cpu }}
  version: {{ $.Values.app.version}}
  {{- end }}
  {{- $map := .Release.name | upper | quote | }}
  map: {{ $map }}
  users: |-
    {{- range tuple "koT9" "moT9" }}
    - {{ . }}
    {{- end}}
    

