apiVersion: v1
kind: Service
metadata: 
  name:  {{ .Values.postgres.name }}-cluster-ip
spec:
  type: ClusterIP
  ports: 
    - port: {{ .Values.postgres.port }}
      protocol: TCP
  selector:
    components: {{ .Values.postgres.components }}
    