apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.postgres.name}}-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.db | b64dec }}
  POSTGRES_USER:  {{ .Values.database.user | b64dec }}
  POSTGRES_PASSWORD:  {{ .Values.database.password | b64dec }}
